FROM free5gc/base as my-base

RUN git clone https://github.com/free5gc/go-gtp5gnl.git && mkdir "go-gtp5gnl/bin" && \
    cd "go-gtp5gnl/cmd/gogtp5g-tunnel" &&  go build -o "${GOPATH}/gtp5g-tunnel" . && \
    cd -

FROM free5gc/upf-base:latest AS builder
FROM golang:1.18.10-bullseye

ENV F5GC_MODULE upf
ENV DEBIAN_FRONTEND noninteractive

# Install UPF dependencies
RUN apt-get update \
    && apt-get install -y libmnl0 libyaml-0-2 iproute2 iptables strace net-tools iputils-ping curl netcat\
    && apt-get clean

# Get Free5GC
RUN git clone --recurse-submodules https://github.com/free5gc/free5gc /free5gc
WORKDIR /free5gc
RUN mkdir -p config/ log/
RUN rm -rf /free5gc/NFs/upf

# Config files volume
VOLUME [ "/free5gc/config" ]
# We bind the upf source as a volume so we can develop on the host and compile in the container
VOLUME [ "/free5gc/NFs/upf" ]
